### ISSUE TITLE
epic: Backlog da Etapa 2

### ISSUE THREAD

**Issue by euaaron** [ICEI-PUC-Minas-PMV-ADS/pmv-ads-2023-1-e3-proj-mov-t4-time5-projgrupo#9]
# Etapa 2

## Revisar

- [ ] documentação de contexto e 
- [ ] especificação do projeto

## Documentar

- [ ] descrever processos e suas respectivas atividades
- [ ] modelar processos de negócio no padrão BPMN
- [ ] elicitar e categorizar requisitos funcionais e não funcionais derivados dos processos organizacionais
- [ ] deverão ser criados tabelas, gráficos ou dashboards com no mínimo 5 indicadores de desempenho e metas para o processo de negócio
- [ ] Seção de Metodologia

## Elaborar

- [ ] Modelo ER (Entidade Relacional) e Esquema Relacional
- [ ] Projeto de Interface (wireframes)
- [ ] Diagrama de Fluxo

## Desenvolver

- [ ] Base do projeto mobile com React Native
- [ ] Componentes base para desenvolvimento da aplicação (design system/identidade visual)
- [ ] Folhas de estilo
- [ ] Layout base das telas, se ter tempo já com a base da navegação e o controle de acesso

**Comment by euaaron** [comment]
Issue fechado pois criei uma issue para cada task.
